eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8085

spring:
  profiles:
    active: local
    include: redis
  application:
    name: notification-service