eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8090
  servlet:
    session:
      cookie:
        name: JSESSIONID_AUTH

spring:
  profiles:
    active: local
    include: auth, redis

  application:
    name: auth-server