eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8000

spring:
  profiles:
    include: jwt, redis
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-server
          uri:
            lb://AUTH-SERVER
          predicates:
            - Path=/api/auth/**, /api/users/**

        - id: notification-service
          uri:
            lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - AuthorizationHeaderFilter
            - AuthorizationGuestFilter
            - RemoveRequestHeader=Cookie

        - id: post-service
          uri:
            lb://POST-SERVICE
          predicates:
            - Path=/api/posts/**, /api/comments/**
          filters:
            - AuthorizationHeaderFilter
            - AuthorizationUserFilter
            - RemoveRequestHeader=Cookie