\eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8089

spring:
  profiles:
    active: local
    include: redis, file
  application:
    name: mail-service