eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8081

spring:
  profiles:
    active: local
    include: file, redis
  application:
    name: post-service